title:        Rails-i8n.org
tagline:      'Interviews, Inspiration, And Tools For The Rails I18n Community'
description:  'An open-source project curating interviews from some of the leading names in the Rails internationalization world.'
url:          http://rails-i18n.org
version:      1.1.1
author:
  name:       'Erez Zukerman'
  email:      'bulk@ezuk.org'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
baseurl:      /rails-i18n.org